package p1;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HelloApp.java
//  @ Date : 2019-12-03
//  @ Author : 
//
//




public class HelloAppEn {
	public static void main(String[] args) {
	MessageBeanEn en=new MessageBeanEn();
	
	en.sayHello("Mr.smith");
	}
}
