package p2;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MassageBean.java
//  @ Date : 2019-12-03
//  @ Author : 
//
//




public interface MessageBean {
	public void sayHello(String name);
}
